// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCredential(arg1) {
  return window['go']['gui']['App']['DeleteCredential'](arg1);
}

export function GetBackend() {
  return window['go']['gui']['App']['GetBackend']();
}

export function GetEnvDefaults() {
  return window['go']['gui']['App']['GetEnvDefaults']();
}

export function GetLoginStatus() {
  return window['go']['gui']['App']['GetLoginStatus']();
}

export function GetLogs() {
  return window['go']['gui']['App']['GetLogs']();
}

export function GetMountStatus() {
  return window['go']['gui']['App']['GetMountStatus']();
}

export function GetVersion() {
  return window['go']['gui']['App']['GetVersion']();
}

export function IsBrowserLoginSupported() {
  return window['go']['gui']['App']['IsBrowserLoginSupported']();
}

export function ListBackends() {
  return window['go']['gui']['App']['ListBackends']();
}

export function ListCredentials() {
  return window['go']['gui']['App']['ListCredentials']();
}

export function ListProjects() {
  return window['go']['gui']['App']['ListProjects']();
}

export function ListTags() {
  return window['go']['gui']['App']['ListTags']();
}

export function Login(arg1, arg2) {
  return window['go']['gui']['App']['Login'](arg1, arg2);
}

export function LoginWithBrowser(arg1) {
  return window['go']['gui']['App']['LoginWithBrowser'](arg1);
}

export function LoginWithCredential(arg1) {
  return window['go']['gui']['App']['LoginWithCredential'](arg1);
}

export function Mount(arg1, arg2, arg3) {
  return window['go']['gui']['App']['Mount'](arg1, arg2, arg3);
}

export function OpenMountpoint() {
  return window['go']['gui']['App']['OpenMountpoint']();
}

export function SetBackend(arg1) {
  return window['go']['gui']['App']['SetBackend'](arg1);
}

export function Sync() {
  return window['go']['gui']['App']['Sync']();
}

export function Unmount() {
  return window['go']['gui']['App']['Unmount']();
}
