// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEnvDefaults() {
  return window['go']['gui']['App']['GetEnvDefaults']();
}

export function GetLoginStatus() {
  return window['go']['gui']['App']['GetLoginStatus']();
}

export function GetLogs() {
  return window['go']['gui']['App']['GetLogs']();
}

export function GetMountStatus() {
  return window['go']['gui']['App']['GetMountStatus']();
}

export function ListProjects() {
  return window['go']['gui']['App']['ListProjects']();
}

export function Login(arg1, arg2) {
  return window['go']['gui']['App']['Login'](arg1, arg2);
}

export function Mount(arg1, arg2, arg3) {
  return window['go']['gui']['App']['Mount'](arg1, arg2, arg3);
}

export function OpenMountpoint() {
  return window['go']['gui']['App']['OpenMountpoint']();
}

export function Sync() {
  return window['go']['gui']['App']['Sync']();
}

export function Unmount() {
  return window['go']['gui']['App']['Unmount']();
}
