// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';
import {model} from '../models';

export function GetEnvDefaults():Promise<Record<string, string>>;

export function GetLoginStatus():Promise<gui.LoginStatus>;

export function GetLogs():Promise<Array<string>>;

export function GetVersion():Promise<string>;

export function GetMountStatus():Promise<gui.MountStatus>;

export function ListProjects():Promise<Array<model.Project>>;

export function Login(arg1:string,arg2:string):Promise<gui.LoginStatus>;

export function Mount(arg1:Array<string>,arg2:string,arg3:boolean):Promise<void>;

export function OpenMountpoint():Promise<void>;

export function Sync():Promise<string>;

export function Unmount():Promise<void>;
