// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';
import {credential} from '../models';
import {model} from '../models';

export function DeleteCredential(arg1:string):Promise<void>;

export function GetBackend():Promise<string>;

export function GetEnvDefaults():Promise<Record<string, string>>;

export function GetLoginStatus():Promise<gui.LoginStatus>;

export function GetLogs():Promise<Array<string>>;

export function GetMountStatus():Promise<gui.MountStatus>;

export function GetVersion():Promise<string>;

export function IsBrowserLoginSupported():Promise<boolean>;

export function ListBackends():Promise<Array<gui.BackendInfo>>;

export function ListCredentials():Promise<Array<credential.CredentialInfo>>;

export function ListProjects():Promise<Array<model.Project>>;

export function ListTags():Promise<Array<model.Tag>>;

export function Login(arg1:string,arg2:string):Promise<gui.LoginStatus>;

export function LoginWithBrowser(arg1:string):Promise<gui.LoginStatus>;

export function LoginWithCredential(arg1:string):Promise<gui.LoginStatus>;

export function Mount(arg1:Array<string>,arg2:string,arg3:boolean):Promise<void>;

export function OpenMountpoint():Promise<void>;

export function SetBackend(arg1:string):Promise<void>;

export function Sync():Promise<string>;

export function Unmount():Promise<void>;
